
<h1>HYPESPARK TERMS OF USE</h1>
    <p>hypespark.com, related advertisement and member services, including, but not limited to, moble phone applications (COLLECTIVELY, THE &ldquo;SITE&rdquo;) ARE PROVIDED SUBJECT TO THESE TERMS OF USE. PLEASE READ THE FOLLOWING INFORMATION CAREFULLY. YOUR CONTINUED USE OF THE SITE WILL IND&shy;ICATE YOUR AGREEMENT TO BE BOUND BY THE TERMS AND CONDITIONS SET FORTH BELOW. IF YOU DO NOT AGREE TO THESE TERMS AND CONDITIONS, PROMPTLY EXIT THE SITE.<br />
    1.	Acceptance<br />
    THESE TERMS OF USE (&ldquo;TERMS OF USE&rdquo;) ARE A LEGALLY BINDING AGREEMENT BETWEEN you (&ldquo;YOU&rdquo; AND &ldquo;YOUR&rdquo;) ANd hypespark, LLC (&ldquo;HypeSpark&rdquo;). BY USING THE SITE, YOU AGREE THAT YOU UNDERSTAND THESE TERMS OF USE, AND THAT YOU CONSENT TO BE BOUND BY ALL OF ITS TERMS AND CONDITIONS. THESE TERMS OF USE SET FORTH YOUR RIGHTS AND OBLIGATIONS WITH RESPECT TO YOUR USE OF AND ACCESS TO THE SITE. IF YOU DO NOT AGREE TO THESE TERMS OF USE, YOU SHOULD NOT USE THE SITE.<br />
    2.	Ownership of the Site; Restrictions on Use<br />
    All pages within the Site and any material made available for download are the property of HypeSpark. The Site is protected by United States and international copyright, patent, and trademark laws. The contents of the Site, including without limitation, links, location data, files, documents, text, photographs, images, audio, video, and any materials accessed through or made available for use or download (collectively, &quot;Content&quot;) may not be copied, distributed, modified, reproduced, published or used, in whole or in part, except for purposes authorized or approved by HypeSpark.<br />
    As a condition of your use of the Site, you warrant to HypeSpark that you will not use the Site for any purpose that is unlawful or prohibited by these Terms of Use. If you breach any of these Terms of Use, your authorization to use the Site automatically terminates.<br />
    You may not use automated systems (e.g., robots, spiders, etc.) to access or &ldquo;harvest&rdquo; information from the Site. You agree not to collect personally identifiable information of other users of the Site or to sell or otherwise exploit that information. You agree not to use the Site in any manner that could damage, disable, overburden, or impair the Site.<br />
    Any rights not expressly granted by these Terms of Use or any user license agreements are reserved by HypeSpark or its affiliates.<br />
    3.	Confidential Information<br />
    You acknowledge that the Site and Content include information which is confidential and proprietary to HypeSpark (&ldquo;Confidential Information&rdquo;). Confidential Information includes Content or other information marked as &ldquo;Confidential&rdquo; or similar label, as well as any other Content or other information which you know or reasonably should know is confidential or proprietary to HypeSpark. If you are not sure whether Content is Confidential Information, please contact an authorized HypeSpark representative for clarification, and do not disclose such Content to any third party until you receive such clarification. You agree to keep all Confidential Information strictly confidential and to not disclose any Confidential Information to any third party without the advance written consent of HypeSpark.<br />
    4.	Accuracy and Integrity of Information <br />
    Although HypeSpark attempts to ensure the integrity and accurateness of the Site, it makes no representations, warranties, or guarantees whatsoever as to the correctness or accuracy of the Site and Content. It is possible that the Site could include typographical errors, inaccuracies, or other errors, and that unauthorized additions, deletions, and alterations could be made to the Site by third parties. In the event that an inaccuracy arises, please inform HypeSpark so that it can be corrected. Any information, Content, service, function, or feature contained on the Site may be discontinued, changed, or updated at any time with or without notice. Additionally, HypeSpark shall have no responsibility or liability for information or Content posted to the Site from any third party.<br />
    5.	Access to Site<br />
    In the event access to the Site or a portion thereof requires a user ID and password (&ldquo;Protected Areas&rdquo;), you agree to access Protected Areas using only your user ID and password on file with HypeSpark. You agree to protect the confidentiality of your user ID and password, not to share or disclose your user ID or password to any third party, and to promptly notify HypeSpark in the event you become aware your user ID or password may have been disclosed to an unauthorized third party or otherwise compromised. Your access to the Site may be revoked by HypeSpark at any time with or without cause. You agree to defend, indemnify and hold HypeSpark harmless from and against all third party claims, damages, and expenses (including reasonable attorneys&rsquo; fees) against or incurred by HypeSpark arising out of your use or access of the Site, or any breach of these Terms of Use.<br />
6.	Relationship Between You and HypeSpark</p>
<p>You and HypeSpark are independent contractors, and nothing in these Terms of Use will create any partnership, joint venture, agency, franchise, sales representative, or employment relationship between the parties. You have no authority to make or accept any offers or representations on HypeSpark&rsquo;s behalf. You will not make any statement that would reasonably contradict anything in this section. You are not an agent of HypeSpark and HypeSpark expressly disclaims responsibility for any conduct by you in violation of these Terms of Use.</p>
<p>7.	Responsibility for Your Content and Links</p>
<p>You are solely responsible for Content you upload to the Site and URLs and links that you upload to the Site (&ldquo;Links&rdquo;). HypeSpark shall have no responsibility for the development, operation, and maintenance of any Content or Links. If you submit or upload any Content or Links, you agree not to: (a) post or transmit anything that is defamatory, abusive, libelous, unlawful, obscene, threatening, harassing, fraudulent, pornographic, harmful, or that could encourage criminal or unethical behavior; (b) submit or upload anything that violates the copyright or intellectual property rights of any person or entity; (c) post or transmit a virus or any other harmful component; or (d) contact individuals through unsolicited e-mail, telephone calls, mailings, or any other method of communication. HypeSpark and its affiliates shall have the perpetual sublicensable right and license to use, copy, display, perform, distribute, modify, adapt, abridge, exploit, and promote Content in any way and in any commercial or non-commercial medium or form without charge. You are responsible for making sure all Content and Links that you originate or require are properly backed up so you have ready access thereto in the event of loss, corruption, or interruption. You agree to defend, indemnify and hold HypeSpark harmless from and against all third party claims, damages, and expenses (including reasonable attorneys&rsquo; fees) against or incurred by HypeSpark arising out of any Content or Links you post or allow to be posted to the Site.</p>
<p>8.	Forms of Promotion and Use of HypeSpark Intellectual Property</p>
<p>You may use any form of promotion you choose to promote Links consistent with these Terms of Use. &ldquo;Impression&rdquo; means a click on a unique Link from a unique IP address. The following activities are not allowed for the purposes of promoting Links or accumulating Impressions: (a) spamming and unsolicited communications; (b) altering by electronic, mechanical, or automated means or other technologies that may now exist or come into existence, Links belonging to or identified with accounts other than your own, or causing the modification or substitution of Links belonging to or identified with accounts other than your own that may reside within or originate from a third party system in the form of bookmarks, cached pages, cookies, or other stored forms that may be passed to the Site through or by said third party systems; (c) using password sites, MP3 sites, other PTC sites, pay to view advertisement sites, URL redirection sites (including Linkbucks, Hyperlinkcash, etc.), or warez sites; (d) creating artificial traffic or bot traffic.</p>
<p>Links and accompanying promotional material may contain HypeSpark trademarks, service marks, or logos. Subject to these Terms of Use, you are granted a limited, non-exclusive, non-transferable license to access, download, display, and transmit such trademarks, service marks, and logos for the sole and exclusive purpose of promoting HypeSpark or Links. </p>
<p>9.	Maximum User Offers and Activity Requirement</p>
<p>You may only participate in [3] offers at a time. Upon exiting an offer, you forfeit any Impressions you have accrued for that offer. Reasons for exiting an offer may include, but are not limited to, expiration of an offer or you wanting to participate in a different offer at a time when you are already participating in the maximum number of allowed offers.</p>
<p>If at any time you do not receive any Impressions for a particular offer within two (2) weeks, you are disqualified from that particular offer, with or without notification from HypeSpark. The two (2) week restriction begins once you agree to the terms of that particular offer and resets upon every Impression one of your Links for that particular offer receives.</p>
<p>10.	Location Information</p>
<p>Use of the Site grants HypeSpark the right to share information regarding your physical location to others. HypeSpark agrees to only share your approximate location (city and state) through the Site, and not your exact location. </p>
<p> HypeSpark is not responsible for any person&rsquo;s actions that result from the sharing of location information. HypeSpark is not liable for any damages to any persons or property which may result from sharing location information. You should use caution and common sense to prevent misuse of location information.</p>
<p>11.	No Duty to Monitor<br />
    You agree that HypeSpark is not liable for Content or Links that are provided by others. HypeSpark has no duty to screen or monitor Content or Links that you or other users may upload or submit. However HypeSpark reserves the right to remove or edit Content or Links for any reason at any time.<br />
    12.	Infringement Notices<br />
    As provided in the Digital Millennium Copyright Act (DMCA), HypeSpark has designated the following individual for notification of potential copyright infringement regarding the Site: <br />
    [contact name, mailing address, telephone, facsimile, and e-mail]<br />
    If you believe any content available through the Site infringes a copyright, please provide the following information to the person identified above (17 U.S.C. &sect; 512):<br />
    12.1		a physical or electronic signature of the copyright owner or authorized agent;<br />
    12.2		identification of the copyrighted work(s) claimed to have been infringed;<br />
    12.3		identification of the material that is claimed to be infringing or to be the subject of the infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit HypeSpark to locate the material;<br />
    12.4		information regarding how HypeSpark may contact you (e.g., mailing address, telephone number, e-mail address);<br />
    12.5		a statement that the copyright owner or its authorized agent has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and<br />
    12.6		a statement that the information in the notification is accurate, and made under penalty of perjury, and, if an agent is providing the notification, a statement that the agent is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.<br />
    13.	Disclaimer of Warranties <br />
    HYPESPARK DOES NOT WARRANT THAT ACCESS TO OR USE OF THE SITE WILL BE UNINTERRUPTED OR ERROR FREE OR THAT DEFECTS IN THE SITE WILL BE CORRECTED. THIS SITE, INCLUDING ANY CONTENT, LINKS, OR INFORMATION CONTAINED WITHIN IT OR ANY SITE-RELATED SERVICE, IS PROVIDED &ldquo;AS IS,&rdquo; WITH ALL FAULTS, WITH NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUALITY OF INFORMATION, QUIET ENJOYMENT, AND TITLE/NON-INFRINGEMENT. HYPESPARK SPECIFICALLY DISCLAIMS ALL LIABILITY FOR ERRORS OR OMISSIONS IN, OR THE MISUSE OR MISINTERPRETATION OF, ANY INFORMATION OBTAINED THROUGH THE SITE. HYPESPARK DOES NOT WARRANT THE ACCURACY, COMPLETENESS, OR TIMELINESS OF THE INFORMATION OBTAINED THROUGH THE SITE. <br />
    YOU ASSUME TOTAL RESPONSIBILITY AND RISK FOR YOUR USE OF THIS SITE AND LINKS. HYPESPARK DOES NOT WARRANT THAT FILES AVAILABLE FOR DOWNLOAD OR LINKS WILL BE FREE OF VIRUSES, WORMS, TROJAN HORSES, OR OTHER DESTRUCTIVE PROGRAMMING. YOU AGREE THAT HYPESPARK SHALL NOT BE LIABLE FOR ANY COST OR DAMAGE ARISING DIRECTLY OR INDIRECTLY FROM ANY SUCH CODE. YOU ARE RESPONSIBLE FOR IMPLEMENTING PROCEDURES SUFFICIENT TO SATISFY YOUR NEEDS FOR DATA BACK UP AND SECURITY. YOU ASSUME TOTAL RESPONSIBILITY AND RISK FOR YOUR USE OF THE SITE AND OF THE INTERNET.<br />
    14.	Limitation of Liability Regarding Use of Site <br />
    HYPESPARK AND ITS AFFILIATES, VENDORS, LICENSORS, DEALERS, AND ANY THIRD PARTIES MENTIONED ON THE SITE ARE NEITHER RESPONSIBLE NOR LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, PUNITIVE, OR OTHER DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, THOSE RESULTING FROM LOST PROFITS, LOST DATA, OR BUSINESS INTERRUPTION) ARISING OUT OF OR RELATING IN ANY WAY TO THE SITE, CONTENT, OR INFORMATION CONTAINED WITHIN THE SITE, OR ANY LINKS, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. YOUR SOLE REMEDY FOR DISSATISFACTION WITH THE SITE, SITE-RELATED SERVICES, OR LINKS IS TO STOP USING THE SITE AND THOSE SERVICES. APPLICABLE LAW MAY NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.<br />
    15.	Links to Other Sites <br />
    HypeSpark makes no representations whatsoever about any other site that you may access through the Site or Links. When you access a non-HypeSpark site, please understand that it is independent from HypeSpark, and that HypeSpark has no control over the content on that site. In addition, a Link to a non-HypeSpark site does not mean that HypeSpark endorses or accepts any responsibility for the content, or the use, of that site. It is up to you to take precautions to ensure that whatever you select for your use or download is free of such items as viruses, worms, Trojan horses, and other destructive programming. If you decide to use or access any Links or non-HypeSpark sites, you do this entirely at your own risk.<br />
    16.	Age of Users<br />
    Children under the age of thirteen (13) may not use the Site and parents or legal guardians may not agree to these Terms of Use on their behalf. If HypeSpark becomes aware that a child under thirteen (13) has provided or attempted to provide HypeSpark with personal information, HypeSpark will use HypeSpark&rsquo;s best efforts to remove the information permanently from HypeSpark&rsquo;s files.</p>
<p>If you are under the age of eighteen (18) but at least thirteen (13) years of age, you may use the Site only under the supervision of a parent or legal guardian who agrees to be bound by these Terms of Use. If you are a parent or legal guardian agreeing to these Terms of Use for the benefit of a child between the ages of thirteen (13) and eighteen (18), be advised that you are fully responsible for his or her use of the Site, including all financial charges and legal liability that he or she may incur.</p>
<p>17.	Payment After Termination</p>
<p>If your use of the Site is terminated, you are not eligible to receive any rewards, coupons, or other forms of payment, even for rewards or coupons earned and Impressions accumulated prior to the date of termination. </p>
<p>18.	Electronic Delivery Statement and Your Consent<br />
    You agree that HypeSpark may provide notices and other information concerning HypeSpark or the Site electronically, including notice to any email address that you may provide.<br />
    19.	International Use<br />
    HypeSpark makes no representation that Content on the Site or Links are appropriate or available for use in locations outside the United States. If you choose to access the Site from a location outside the U.S., you do so on your own initiative, and you are responsible for compliance with local laws.<br />
    20.	Privacy Policy<br />
    Information that you provide or that HypeSpark collects about you, in connection with your access to and use of the Site, is subject to HypeSpark&rsquo;s Privacy Policy [this should be a live link to the HypeSpark Privacy Policy], the terms of which are hereby incorporated into these Terms of Use by reference. Your use of the Site signifies your continuing consent to HypeSpark&rsquo;s Privacy Policy.<br />
    21.	Revisions; General <br />
    HypeSpark reserves the right, in its sole discretion, to terminate your access to all or part of this Site, with or without cause, and with or without notice. In the event that any of these Terms of Use are held by a court or other tribunal of competent jurisdiction to be unenforceable, such provisions shall be limited or eliminated to the minimum extent necessary so that these Terms of Use shall otherwise remain in full force and effect. These Terms of Use constitute the entire agreement between HypeSpark and you pertaining to the subject matter hereof. In its sole discretion, HypeSpark may from time-to-time revise these Terms of Use by updating this page. You should, therefore, periodically visit this page to review the current Terms of Use, so you are aware of any such revisions to which you are bound. Certain provisions of these Terms of Use may be superseded by expressly designated legal notices or terms located on particular pages within the Site. In the event of any dispute or claim relating to the Site or these Terms of Use, you agree to resolution of such dispute in the state or federal courts located in Wisconsin in accordance with Wisconsin law. Any cause of action brought by you against HypeSpark or its affiliates must be instituted within one (1) year after the cause of action arises or be deemed forever waived and barred.</p>
<p></p>